### ISSUE TITLE
add comments

### ISSUE THREAD

**Issue by Erol314** [brendt/rfc-vote#107]
Feature request:
This may be out of scope of this project, but
how about adding the ability comment under the vote? 
possible restrictions to avoid clutter: 
- no nested comments, only 1 level . 
- 1 comment per user for other user's argument.

**Comment by olleharstedt** [comment]
At work we sometimes use google docs to continue arguments. There you can mark words and create a comment list from it. One recent relevant example where this could be useful:

> this proposal puts forward messy syntax that isn't clear

"messy syntax" here is not very precise. It would be nice to create a comment from those words and ask for clarification. :) Just my 2 cents. ^^

**Comment by brendt** [comment]
Work in progress update:

- `ArgumentComment` is a thing now
- Comments are hidden by default, but can be shown on a per-argument basis
- I want to keep comments as plain as possible, that means no markdown support.

<img width="1209" alt="Screenshot 2023-08-18 at 11 46 49" src="https://github.com/brendt/rfc-vote/assets/6905297/af46dc86-da9f-4592-8c31-8d9265c4da28">

### Todos

- [ ] Creating a comment
- [ ] Should comments always be shown?
- [ ] Styling
- [ ] Being able to edit or delete your comment (or as an admin)
- [ ] Styling
- [ ] Add a way to visualise whether there are new comments? Or at least have a way that notifies users when there are new comments on their arguments, and when an argument you've commented on, received a new comment

**Comment by brendt** [comment]
Branch is here, btw: https://github.com/brendt/rfc-vote/tree/argument-comments

**Comment by nielsdos** [comment]
FWIW, I think from the perspective of an RFC author, it's important to be able to comment on comments (and have them always shown). For example to clear up confusion/misunderstanding or notify that a certain concern has been addressed by an edit in the RFC text.

**Comment by brendt** [comment]
Makes sense to always show them. Though I'm afraid the list will grow way too big. Maybe there's a compromise where we show comments for argument you've voted on, or always show the first comment

**Comment by olleharstedt** [comment]
One idea:

* Show max 3 first comments with a link-button to view more
* Add an option to always hide comments

Too much work?

**Comment by brendt** [comment]
No, sounds like a good idea 👍
